"""Registry-backed runner for the native PDF table candidate."""

from __future__ import annotations

from concurrent.futures import FIRST_COMPLETED, Future, ProcessPoolExecutor, wait
from dataclasses import dataclass
from datetime import datetime
import hashlib
import json
from pathlib import Path
import time
from typing import Callable
from uuid import uuid4

import polars as pl

from chongzu import paths
from chongzu.cancellation import CancellationRequested, check_cancel
from chongzu.registry import Registry, canonical_source_root, utc_now
from chongzu.worker_runtime import configure_hidden_worker_executable

from ..artifacts import artifact_absolute
from ..models import StructuredSource
from .img2table_extractor import (
    EXTRACTOR_NAME,
    EXTRACTOR_VERSION,
    PDFTableConfig,
    PDFTableExtractionResult,
    _issue,
    extract_pdf_tables_file,
)
from .runner import extract_pdf
from .table_quality import (
    DetectedTable,
    ExpectedTable,
    GroundTruthScore,
    load_ground_truth,
    score_tables,
)


MAX_PDF_TABLE_WORKERS = 4


class PDFTableExtractionError(RuntimeError):
    pass


def normalize_pdf_table_workers(workers: int | None) -> int:
    value = 1 if workers is None else int(workers)
    if value < 1 or value > MAX_PDF_TABLE_WORKERS:
        raise ValueError(f"PDF table workers must be between 1 and {MAX_PDF_TABLE_WORKERS}")
    return value


def pdf_table_extraction_identity(source: StructuredSource, config: PDFTableConfig) -> str:
    payload = json.dumps(
        {
            "file_id": source.file_id,
            "content_sha256": source.content_sha256,
            "business_format": source.business_format,
            "extractor": EXTRACTOR_NAME,
            "extractor_version": EXTRACTOR_VERSION,
            "config_version": paths.PDF_TABLE_CONFIG_VERSION,
            "config": config.as_dict(),
            # Registry migrations are additive metadata changes.  Keep raw
            # extraction identities stable so a Catalog upgrade never forces
            # native PDF table candidates to be recomputed.
            "registry_schema_version": paths.EXTRACTION_IDENTITY_SCHEMA_VERSION,
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _source_from_row(row: dict[str, object], workspace_root: Path) -> StructuredSource:
    return StructuredSource(
        file_id=str(row["file_id"]),
        content_sha256=str(row["sha256"]),
        source_root=str(row["source_root"]),
        relative_path=str(row["relative_path"]),
        business_format="pdf",
        size_bytes=int(row["size_bytes"] or 0),
        mtime_ns=int(row["mtime_ns"] or 0),
        workspace_root=workspace_root,
    )


def _runtime_dependency_size() -> int:
    total = 0
    try:
        for item in paths.PACKAGES_ROOT.rglob("*"):
            # Report the portable distribution payload, not generated bytecode
            # or uv's target-install marker.  This keeps benchmark output
            # comparable with the footprint recorded in docs/RUNTIME.md.
            if item.is_file() and "__pycache__" not in item.parts and item.name != ".lock":
                total += item.stat().st_size
    except OSError:
        return 0
    return total


def _profile_route(profile_record: dict[str, object] | None) -> tuple[str, int, list[int], str]:
    if not profile_record:
        return "unknown", 0, [], "phase4a_profile_missing_deferred_to_ocr"
    profile = profile_record.get("profile")
    if not isinstance(profile, dict):
        return "unknown", 0, [], "phase4a_profile_invalid_deferred_to_ocr"
    classification = str(profile.get("classification") or "unknown")
    page_count = int(profile.get("page_count") or 0)
    if classification in {"native_text", "mixed"}:
        # Phase 4A already inspected every page. Only pages carrying explicit
        # table evidence may reach img2table; native text alone is not a table
        # signal. This is the precision-first fast path for ordinary PDFs.
        candidate_pages: list[int] = []
        page_records = profile.get("pages")
        if isinstance(page_records, list):
            for record in page_records:
                if not isinstance(record, dict) or not record.get("possible_table_candidate"):
                    continue
                try:
                    page_number = int(record.get("page_number"))
                except (TypeError, ValueError):
                    continue
                if 1 <= page_number <= page_count:
                    candidate_pages.append(page_number - 1)
        candidate_pages = sorted(set(candidate_pages))
        if candidate_pages:
            reason = (
                "phase4a_native_table_evidence"
                if classification == "native_text"
                else "phase4a_mixed_native_table_evidence"
            )
            return classification, page_count, candidate_pages, reason
        return classification, page_count, [], "no_table_evidence"
    if classification == "suspected_scanned":
        return classification, page_count, [], "phase4a_suspected_scanned_deferred_to_ocr"
    # A profile with pages but no reliable classification is safe to probe via
    # the native candidate. A missing/empty profile has no facts and is
    # deferred instead of pretending OCR happened.
    if page_count:
        return classification, page_count, list(range(page_count)), "phase4a_unknown_native_candidate"
    return classification, page_count, [], "phase4a_unknown_deferred_to_ocr"


def _artifacts_exist(reusable: dict[str, object], workspace_root: Path) -> bool:
    tables = reusable.get("tables") or []
    table_count = int(reusable.get("table_count") or 0)
    if table_count == 0:
        return True
    if len(tables) < table_count:
        return False
    artifacts = reusable.get("artifacts") or []
    try:
        return bool(artifacts) and all(artifact_absolute(str(item), workspace_root).is_file() for item in artifacts)
    except (OSError, ValueError):
        return False


def _extract_one(
    source: StructuredSource,
    run_id: str,
    identity: str,
    page_indexes: list[int],
    classification: str,
    route_reason: str,
    config: PDFTableConfig,
) -> PDFTableExtractionResult:
    try:
        before = source.path.stat()
    except OSError as exc:
        return PDFTableExtractionResult(
            source=source,
            extraction_run_id=run_id,
            extraction_identity=identity,
            route_reason=route_reason,
            profile_classification=classification,
            pages_attempted=len(page_indexes),
            status="failed",
            error_category="source_stat_error",
            error_message=str(exc),
        )
    if (before.st_size, before.st_mtime_ns) != (source.size_bytes, source.mtime_ns):
        return PDFTableExtractionResult(
            source=source,
            extraction_run_id=run_id,
            extraction_identity=identity,
            route_reason=route_reason,
            profile_classification=classification,
            pages_attempted=len(page_indexes),
            status="failed",
            error_category="source_changed_after_scan",
            error_message="source size or mtime changed after the automatic registry scan",
        )
    result = extract_pdf_tables_file(
        source,
        run_id,
        identity,
        page_indexes=page_indexes,
        profile_classification=classification,
        route_reason=route_reason,
        config=config,
    )
    try:
        after = source.path.stat()
    except OSError as exc:
        result.status = "failed"
        result.assets.clear()
        result.detected_tables.clear()
        result.issues.clear()
        result.error_category = "source_stat_error"
        result.error_message = str(exc)
        return result
    if (after.st_size, after.st_mtime_ns) != (before.st_size, before.st_mtime_ns):
        result.status = "failed"
        result.assets.clear()
        result.detected_tables.clear()
        result.issues.clear()
        result.error_category = "source_changed_during_extraction"
        result.error_message = "source size or mtime changed while it was being extracted"
    return result


def _deferred_result(
    source: StructuredSource,
    run_id: str,
    identity: str,
    classification: str,
    page_count: int,
    route_reason: str,
) -> PDFTableExtractionResult:
    result = PDFTableExtractionResult(
        source=source,
        extraction_run_id=run_id,
        extraction_identity=identity,
        route_reason=route_reason,
        profile_classification=classification,
        pages_attempted=0,
        pages_deferred=page_count,
        status="deferred_to_ocr",
        warnings=[
            {
                "candidate_status": "candidate",
                "deferred_to_ocr": True,
                "ocr_enabled": False,
                "reason": route_reason,
            }
        ],
    )
    result.issues.append(
        _issue(
            source=source,
            asset_id=f"pdf-table:{source.file_id}",
            issue_type="deferred_to_ocr",
            evidence={
                "classification": classification,
                "page_count": page_count,
                "route_reason": route_reason,
            },
        )
    )
    return result


def _no_table_result(
    source: StructuredSource,
    run_id: str,
    identity: str,
    classification: str,
    page_count: int,
) -> PDFTableExtractionResult:
    """Persist a normal, successful zero-table result without opening img2table."""

    return PDFTableExtractionResult(
        source=source,
        extraction_run_id=run_id,
        extraction_identity=identity,
        route_reason="no_table_evidence",
        profile_classification=classification,
        pages_attempted=0,
        status="successful",
        warnings=[
            {
                "candidate_status": "not_candidate",
                "table_count": 0,
                "page_count": page_count,
                "reason": "no_table_evidence",
            }
        ],
    )


def _read_reused_tables(reusable: dict[str, object], workspace_root: Path) -> list[DetectedTable]:
    detected: list[DetectedTable] = []
    for table in reusable.get("tables") or []:
        if not isinstance(table, dict):
            continue
        raw_path = table.get("raw_artifact_path")
        if not raw_path:
            continue
        try:
            frame = pl.read_parquet(artifact_absolute(str(raw_path), workspace_root))
            metadata_path = table.get("metadata_artifact_path")
            metadata = (
                json.loads(artifact_absolute(str(metadata_path), workspace_root).read_text(encoding="utf-8"))
                if metadata_path
                else {}
            )
            page_number = int(table.get("page_number") or metadata.get("page_number") or 1)
            table_index = int(metadata.get("table_index", 0))
            rows = tuple(tuple(row) for row in frame.rows())
            detected.append(
                DetectedTable(
                    page_number=page_number,
                    table_index=table_index,
                    rows=rows,
                    table_id=str(table.get("table_id")),
                )
            )
        except (OSError, ValueError, TypeError, json.JSONDecodeError):
            continue
    return detected


@dataclass
class PDFTableExtractionSummary:
    source_root: str
    pdfs_considered: int = 0
    pdfs_attempted: int = 0
    reused: int = 0
    deferred_to_ocr: int = 0
    deferred_pages: int = 0
    pages: int = 0
    pages_attempted: int = 0
    total_bytes: int = 0
    expected_tables: int | None = None
    detected_tables: int = 0
    true_positives: int | None = None
    false_negatives: int | None = None
    obvious_false_positives: int | None = None
    exact_shape_matches: int | None = None
    row_count_matches: int | None = None
    column_count_matches: int | None = None
    exact_cell_matches: int | None = None
    normalized_cell_matches: int | None = None
    missing_cells: int | None = None
    extra_cells: int | None = None
    extraction_failures: int = 0
    table_assets: int = 0
    rows: int = 0
    cells: int = 0
    quality_issues: int = 0
    discovery_scan_ms: float = 0.0
    extraction_ms: float = 0.0
    normalization_ms: float = 0.0
    parquet_write_ms: float = 0.0
    registry_write_ms: float = 0.0
    wall_time_ms: float = 0.0
    runtime_dependency_size_bytes: int = 0

    def _add_score(self, score: GroundTruthScore) -> None:
        fields = (
            "expected_tables",
            "true_positives",
            "false_negatives",
            "obvious_false_positives",
            "exact_shape_matches",
            "row_count_matches",
            "column_count_matches",
            "exact_cell_matches",
            "normalized_cell_matches",
            "missing_cells",
            "extra_cells",
        )
        for field_name in fields:
            current = getattr(self, field_name)
            setattr(self, field_name, int(current or 0) + int(getattr(score, field_name)))

    def benchmark_metrics(self) -> dict[str, int | float | str | None]:
        seconds = self.wall_time_ms / 1000.0 if self.wall_time_ms else 0.0
        return {
            "PDFs considered": self.pdfs_considered,
            "PDFs attempted": self.pdfs_attempted,
            "reused": self.reused,
            "deferred to OCR": self.deferred_to_ocr,
            "deferred pages": self.deferred_pages,
            "pages": self.pages,
            "total bytes": self.total_bytes,
            "pages attempted": self.pages_attempted,
            "expected tables": self.expected_tables if self.expected_tables is not None else "not provided",
            "tables detected": self.detected_tables,
            "true positives": self.true_positives if self.true_positives is not None else "not provided",
            "false negatives": self.false_negatives if self.false_negatives is not None else "not provided",
            "obvious false positives": self.obvious_false_positives if self.obvious_false_positives is not None else "not provided",
            "exact shape matches": self.exact_shape_matches if self.exact_shape_matches is not None else "not provided",
            "row count matches": self.row_count_matches if self.row_count_matches is not None else "not provided",
            "column count matches": self.column_count_matches if self.column_count_matches is not None else "not provided",
            "exact cell matches": self.exact_cell_matches if self.exact_cell_matches is not None else "not provided",
            "normalized cell matches": self.normalized_cell_matches if self.normalized_cell_matches is not None else "not provided",
            "missing cells": self.missing_cells if self.missing_cells is not None else "not provided",
            "extra cells": self.extra_cells if self.extra_cells is not None else "not provided",
            "extraction failures": self.extraction_failures,
            "table assets": self.table_assets,
            "rows": self.rows,
            "cells": self.cells,
            "extraction ms": self.extraction_ms,
            "normalization ms": self.normalization_ms,
            "parquet write ms": self.parquet_write_ms,
            "registry write ms": self.registry_write_ms,
            "wall time ms": self.wall_time_ms,
            "runtime dependency size": self.runtime_dependency_size_bytes,
            "pages/sec": self.pages / seconds if seconds else 0.0,
            "MB/sec": (self.total_bytes / (1024 * 1024)) / seconds if seconds else 0.0,
        }


def _record_result(
    *,
    registry: Registry,
    summary: PDFTableExtractionSummary,
    result: PDFTableExtractionResult,
    started_at: datetime,
    force: bool,
    expected: tuple[ExpectedTable, ...] | None,
) -> None:
    score = score_tables(expected, result.detected_tables) if expected is not None else None
    if score is not None:
        result.ground_truth_summary = score.as_dict()
    registry_started = time.perf_counter_ns()
    registry.record_pdf_table_result(
        result,
        started_at=started_at,
        finished_at=utc_now(),
        force=force,
    )
    summary.registry_write_ms += (time.perf_counter_ns() - registry_started) / 1_000_000
    summary.extraction_ms += result.timings.extraction_ms
    summary.normalization_ms += result.timings.normalization_ms
    summary.parquet_write_ms += result.timings.parquet_write_ms
    summary.pages_attempted += result.pages_attempted
    if result.status == "deferred_to_ocr":
        summary.deferred_to_ocr += 1
        summary.deferred_pages += result.pages_deferred
    summary.quality_issues += len(result.issues)
    if result.status == "failed":
        summary.extraction_failures += 1
    elif result.status == "deferred_to_ocr":
        pass
    else:
        summary.pdfs_attempted += 1
    summary.detected_tables += len(result.assets)
    summary.table_assets += len(result.assets)
    summary.rows += result.total_rows
    summary.cells += result.total_cells
    if score is not None:
        summary._add_score(score)


def extract_pdf_tables(
    source: Path | str,
    *,
    workers: int | None = None,
    force: bool = False,
    registry_path: Path | str | None = None,
    workspace_root: Path | str | None = None,
    ground_truth: dict[str, tuple[ExpectedTable, ...]] | None = None,
    config: PDFTableConfig | None = None,
    selected_relative_paths: set[str] | None = None,
    _scan_summary=None,
    progress_callback: Callable[..., None] | None = None,
    cancel_event=None,
) -> PDFTableExtractionSummary:
    """Ensure Phase 4A facts exist, then run the img2table candidate.

    ``selected_relative_paths`` is a benchmark-only filter.  The source is
    still scanned as a whole and no files are copied into a staging folder;
    only the registry-backed candidate jobs listed by this set are submitted.
    The default ``None`` preserves the normal full-source extraction command.
    """

    wall_started = time.perf_counter_ns()
    worker_count = normalize_pdf_table_workers(workers)
    candidate_config = config or PDFTableConfig()
    registry_file = Path(registry_path or paths.REGISTRY_PATH).resolve()
    workspace = Path(workspace_root or paths.WORKSPACE_ROOT).resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    try:
        text_summary = extract_pdf(
            source,
            workers=min(worker_count, 4),
            force=False,
            registry_path=registry_file,
            workspace_root=workspace,
            _scan_summary=_scan_summary,
            progress_callback=progress_callback,
            cancel_event=cancel_event,
        )
    except CancellationRequested:
        raise
    except Exception as exc:
        raise PDFTableExtractionError(str(exc)) from exc
    source_root = canonical_source_root(source, require_directory=True)
    summary = PDFTableExtractionSummary(
        source_root=source_root,
        discovery_scan_ms=text_summary.discovery_scan_ms,
        total_bytes=0,
        runtime_dependency_size_bytes=_runtime_dependency_size(),
    )
    configure_hidden_worker_executable()
    registry = Registry.open(registry_file, initialize=False)
    try:
        registry.recover_incomplete_extractions(source_root)
        rows = registry.pdf_candidates(source_root)
        if selected_relative_paths is not None:
            rows = [row for row in rows if str(row["relative_path"]) in selected_relative_paths]
        summary.pdfs_considered = len(rows)
        summary.total_bytes = sum(int(row["size_bytes"] or 0) for row in rows)
        completed = 0

        def emit(file_name: str | None, substage: str) -> None:
            if progress_callback is None:
                return
            progress = 0.45 + (0.15 * completed / max(1, len(rows)))
            try:
                progress_callback(
                    "extract",
                    progress,
                    current_file=file_name,
                    completed=completed,
                    total=len(rows),
                    current_substage=substage,
                )
            except TypeError:
                progress_callback("extract", progress)
        sources = iter(_source_from_row(row, workspace) for row in rows)
        pending: dict[
            Future[PDFTableExtractionResult],
            tuple[
                StructuredSource,
                datetime,
                bool,
                tuple[ExpectedTable, ...] | None,
                str,
                str,
                str,
                str,
            ],
        ] = {}
        exhausted = False
        executor = ProcessPoolExecutor(max_workers=worker_count)
        try:
            while pending or not exhausted:
                check_cancel(cancel_event)
                while not exhausted and len(pending) < worker_count * 2:
                    check_cancel(cancel_event)
                    try:
                        table_source = next(sources)
                    except StopIteration:
                        exhausted = True
                        break
                    emit(table_source.relative_path, "检查 PDF 表格证据")
                    profile_record = registry.current_pdf_profile(
                        table_source.file_id, table_source.content_sha256
                    )
                    classification, page_count, page_indexes, route_reason = _profile_route(profile_record)
                    summary.pages += page_count
                    identity = pdf_table_extraction_identity(table_source, candidate_config)
                    # An annotation sidecar may intentionally cover only a
                    # representative subset.  A missing key is therefore
                    # unscored; an explicit empty list still means a known
                    # no-table negative control.
                    expected = (
                        ground_truth.get(table_source.relative_path)
                        if ground_truth is not None
                        else None
                    )
                    reusable = None if force else registry.reusable_pdf_table_extraction(identity)
                    if reusable is not None and _artifacts_exist(reusable, workspace):
                        summary.reused += 1
                        status = str(reusable.get("status") or "successful")
                        if status == "deferred_to_ocr":
                            summary.deferred_to_ocr += 1
                            summary.deferred_pages += page_count
                        else:
                            summary.pdfs_attempted += 1
                        table_rows = sum(int(item.get("row_count") or 0) for item in reusable.get("tables") or [])
                        table_cells = sum(
                            int(item.get("row_count") or 0) * int(item.get("column_count") or 0)
                            for item in reusable.get("tables") or []
                        )
                        summary.detected_tables += int(reusable.get("table_count") or 0)
                        summary.table_assets += int(reusable.get("table_count") or 0)
                        summary.rows += table_rows
                        summary.cells += table_cells
                        summary.quality_issues += int(reusable.get("quality_issue_count") or 0)
                        if expected is not None:
                            reused_detected = _read_reused_tables(reusable, workspace)
                            summary._add_score(score_tables(expected, reused_detected))
                        completed += 1
                        emit(table_source.relative_path, "复用已有表格结果")
                        continue
                    run_id = f"xrun_{uuid4().hex}"
                    started_at = utc_now()
                    registry_started = time.perf_counter_ns()
                    registry.start_pdf_table_extraction(
                        extraction_run_id=run_id,
                        extraction_identity=identity,
                        source=table_source,
                        extractor=EXTRACTOR_NAME,
                        extractor_version=EXTRACTOR_VERSION,
                        started_at=started_at,
                        force=force,
                    )
                    summary.registry_write_ms += (time.perf_counter_ns() - registry_started) / 1_000_000
                    if not page_indexes and route_reason == "no_table_evidence":
                        result = _no_table_result(
                            table_source,
                            run_id,
                            identity,
                            classification,
                            page_count,
                        )
                        _record_result(
                            registry=registry,
                            summary=summary,
                            result=result,
                            started_at=started_at,
                            force=force,
                            expected=expected,
                        )
                        completed += 1
                        emit(table_source.relative_path, "未检测到表格")
                        continue
                    if not page_indexes:
                        # Missing/invalid Phase 4A facts (including a corrupt
                        # PDF that could not be profiled) are isolated as a
                        # deferred candidate, never reported as a successful
                        # empty extraction.
                        result = _deferred_result(
                            table_source,
                            run_id,
                            identity,
                            classification,
                            page_count,
                            route_reason,
                        )
                        _record_result(
                            registry=registry,
                            summary=summary,
                            result=result,
                            started_at=started_at,
                            force=force,
                            expected=expected,
                        )
                        completed += 1
                        emit(table_source.relative_path, "等待 OCR 表格路由")
                        continue
                    future = executor.submit(
                        _extract_one,
                        table_source,
                        run_id,
                        identity,
                        page_indexes,
                        classification,
                        route_reason,
                        candidate_config,
                    )
                    pending[future] = (
                        table_source,
                        started_at,
                        force,
                        expected,
                        run_id,
                        identity,
                        classification,
                        route_reason,
                    )
                if not pending:
                    continue
                done, _ = wait(tuple(pending), timeout=0.1, return_when=FIRST_COMPLETED)
                for future in done:
                    (
                        table_source,
                        started_at,
                        was_forced,
                        expected,
                        run_id,
                        identity,
                        classification,
                        route_reason,
                    ) = pending.pop(future)
                    try:
                        result = future.result()
                    except Exception as exc:  # isolate one native candidate failure
                        result = PDFTableExtractionResult(
                            source=table_source,
                            extraction_run_id=run_id,
                            extraction_identity=identity,
                            route_reason=route_reason,
                            profile_classification=classification,
                            pages_attempted=0,
                            status="failed",
                            error_category="worker_error",
                            error_message=str(exc),
                        )
                    _record_result(
                        registry=registry,
                        summary=summary,
                        result=result,
                        started_at=started_at,
                        force=was_forced,
                        expected=expected,
                    )
                    completed += 1
                    emit(table_source.relative_path, "表格提取完成")
        except BaseException:
            for future in pending:
                future.cancel()
            executor.shutdown(wait=False, cancel_futures=True)
            raise
        else:
            executor.shutdown(wait=True)
    finally:
        registry.close()
    summary.wall_time_ms = (time.perf_counter_ns() - wall_started) / 1_000_000
    return summary
