"""Application services used by the local HTTP API.

The services deliberately sit above the registry and extraction coordinators.
HTTP handlers depend on these stable operations rather than on DuckDB or
Parquet implementation details.
"""

from .catalog import CatalogService
from .analysis import (
    ANALYSIS_ACTION_CONTRACT_VERSION,
    ANALYSIS_PROMPT_VERSION,
    MAX_ANALYSIS_HISTORY_LIMIT,
    MAX_ANALYSIS_STEPS,
    AnalysisExecutionError,
    AnalysisOrchestrator,
    AnalysisRunStore,
    AnalysisService,
    AnalysisServiceError,
    normalize_analysis_request,
    validate_analysis_action,
)
from .process import ProcessTaskManager, SourceValidationError, TaskAdmissionError, validate_source_directory
from .report import (
    MAX_REPORT_ANALYSIS_RUNS,
    MAX_REPORT_ARTIFACT_BYTES,
    MAX_REPORT_EVIDENCE,
    MAX_REPORT_MODEL_REFERENCE_BYTES,
    MAX_REPORT_SQL_RESULT_BYTES,
    MAX_REPORT_SQL_ROWS,
    REPORT_ACTION_CONTRACT_VERSION,
    REPORT_PROMPT_VERSION,
    REPORT_RENDER_VERSION,
    REPORT_SCHEMA_VERSION,
    ReportComposer,
    ReportExecutionError,
    ReportRunStore,
    new_report_id,
    new_report_run_id,
    render_report_html,
    render_report_markdown,
    validate_report_payload,
)
from .quality import QualityService
from .reset import WorkspaceResetError, WorkspaceResetService
from .sql import (
    SqlAssetError,
    SqlExecutionError,
    SqlQueryService,
    SqlBenchmark,
    SqlSchemaResponse,
    SqlServiceError,
    SqlTimeoutError,
    SqlValidationError,
    verify_sql_sandbox,
    run_sql_benchmark,
)

__all__ = [
    "CatalogService",
    "AnalysisService",
    "AnalysisServiceError",
    "AnalysisExecutionError",
    "AnalysisOrchestrator",
    "AnalysisRunStore",
    "ANALYSIS_ACTION_CONTRACT_VERSION",
    "ANALYSIS_PROMPT_VERSION",
    "MAX_ANALYSIS_HISTORY_LIMIT",
    "MAX_ANALYSIS_STEPS",
    "normalize_analysis_request",
    "validate_analysis_action",
    "ProcessTaskManager",
    "QualityService",
    "WorkspaceResetError",
    "WorkspaceResetService",
    "SqlAssetError",
    "SqlExecutionError",
    "SqlQueryService",
    "SqlBenchmark",
    "SqlSchemaResponse",
    "SqlServiceError",
    "SqlTimeoutError",
    "SqlValidationError",
    "SourceValidationError",
    "TaskAdmissionError",
    "validate_source_directory",
    "ReportComposer",
    "ReportExecutionError",
    "ReportRunStore",
    "new_report_id",
    "new_report_run_id",
    "render_report_html",
    "render_report_markdown",
    "validate_report_payload",
    "REPORT_ACTION_CONTRACT_VERSION",
    "REPORT_PROMPT_VERSION",
    "REPORT_RENDER_VERSION",
    "REPORT_SCHEMA_VERSION",
    "MAX_REPORT_ANALYSIS_RUNS",
    "MAX_REPORT_ARTIFACT_BYTES",
    "MAX_REPORT_EVIDENCE",
    "MAX_REPORT_MODEL_REFERENCE_BYTES",
    "MAX_REPORT_SQL_RESULT_BYTES",
    "MAX_REPORT_SQL_ROWS",
    "verify_sql_sandbox",
    "run_sql_benchmark",
]
